### ISSUE TITLE
Modal operations are denial of service attacks

### ISSUE THREAD

**Issue by pdbj** [LLNL/MacPatch#84]
Hello Folks,

MP occasionally takes over the machine for a scan and patch, completely denying access and use for extended periods of time.  The two behaviors I've observed are forced reboots and a modal process on wake from sleep.  

These are problematic for many reasons:
1.  Forced reboots cause work in progress to be lost.  Yes, applications should be better about restoring state, but the reality is many do not.
2.  The network may be unavailable (not connected), or very poor performance, or expensive, or needed for something else at the moment.
3.  The battery may be low, or recharge not imminent
4. Time-critical work needs to be done (looking up a flight reservation to resolve a boarding pass issue)

The last time this happened it took 50 minutes, starting 10 min before a conference call.  2. and 3. are obviously a bad combination...  Our help desk says "reboot often, daily".  Not helpful.

I understand the desire to scan and patch in a timely way, but forced DoS is not acceptable.  It's ok for MP to announce that a scan is required, within a reasonable time period, such as a day, but it has to give me a chance to choose when it's convenient to do that, not lock up the machine for extended periods with no warning.

**Comment by cheizer** [comment]
Hi Peter,
I would love to understand this better to help you and others. So thanks for all of the comments.

By design, MP only forces a reboot if no one is logged in to the system that way no work should ever be lost.  Your comment on network and battery are great. I can add additional support for checking network bandwidth and checking if the system is running on battery.  

Now, if you want to delay or put off the scan & patch you can simply disable the the scan and patch task. A scan will still occur, and notify that patches are needed. At that point you can use the Self Patch application to install all updates.

I'm a little perplexed on the amount of time the scan and patch are taking. I have not normally seen the agent take that much time. Nor have I seen it lock up the system.
